### ISSUE TITLE
App crashes when updating

### ISSUE THREAD

**Issue by heizenbrg** [chikorita157/malupdaterosx-cocoa#5] opened 2015-02-03 21:48 UTC
App crashes when clicking on update now.  
Sometimes it does not update automatically.

**Comment by chikorita157** [comment] 2015-02-03 22:26
What version are you using and can you give me the crash log.

**Comment by chikorita157** [comment] 2015-02-05 21:17
What is the status of the crash? Have you attempt an update yet?

**Comment by heizenbrg** [comment] 2015-02-05 21:55
Here is one the crash reports, I got the others if you need them.  
Basically when I notice it's not automatically updating, I click on Update now.  
The command greys out saying updating.. but then crashes.

Process:               MAL Updater OS X [278]
Path:                  /Applications/MAL Updater OS X.app/Contents/MacOS/MAL Updater OS X
Identifier:            com.chikorita157.MAL-Updater-OS-X
Responsible:           MAL Updater OS X [278]
5   MAL Updater OS X                    0x0000000109d01cff -[EasyNSURLConnection encodeArraywithDictionaries:] + 375
6   MAL Updater OS X                    0x0000000109d0188a -[EasyNSURLConnection startFormRequest] + 266
7   MAL Updater OS X                    0x0000000109cfd1ca -[MyAnimeList updatetitle:confirming:] + 1010
8   MAL Updater OS X                    0x0000000109cfa0eb -[MyAnimeList scrobble] + 1995
9   MAL Updater OS X                    0x0000000109cf4327 __41-[MAL_Updater_OS_XAppDelegate firetimer:]_block_invoke + 379
       0x109cf0000 -        0x109d1bfff +com.chikorita157.MAL-Updater-OS-X (2.2.1 - 2.2.1) <06C3E93E-9797-3843-ABCC-BF95B8C8C1C3> /Applications/MAL Updater OS X.app/Contents/MacOS/MAL Updater OS X
       0x109d4b000 -        0x109d68ff7 +moe.ateliershiori.anitomy-osx (1.0 - 1) <1A8405C1-8518-3D2B-BC16-C097A506B08F> /Applications/MAL Updater OS X.app/Contents/Frameworks/anitomy-osx.framework/Versions/A/anitomy-osx
       0x109d81000 -        0x109e06ff7 +isao.sonobe.OgreKit (2.1.4) <035D39AB-19B7-3811-A8B3-1BBEF344EEEA> /Applications/MAL Updater OS X.app/Contents/Frameworks/OgreKit.framework/Versions/A/OgreKit
       0x109e23000 -        0x109e51ff7 +org.andymatuschak.Sparkle (1.8.0 - 0b186dc) <3E8C44BB-5A29-3577-AC71-89DFAB4ECD19> /Applications/MAL Updater OS X.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle

**Comment by chikorita157** [comment] 2015-02-05 22:01
Can you also provide the output from the console.app. You can do this by going into console app and typing MAL Updater OS X in the filter. Also, provide what file name you are trying to update.

**Comment by heizenbrg** [comment] 2015-02-05 22:15
CRASH REPORT
Process:               MAL Updater OS X [279]
Path:                  /Applications/MAL Updater OS
X.app/Contents/MacOS/MAL Updater OS X
Identifier:            com.chikorita157.MAL-Updater-OS-X
Responsible:           MAL Updater OS X [279]
5   MAL Updater OS X                    0x000000010a2c0cff
-[EasyNSURLConnection encodeArraywithDictionaries:] + 375
6   MAL Updater OS X                    0x000000010a2c088a
-[EasyNSURLConnection startFormRequest] + 266
7   MAL Updater OS X                    0x000000010a2bc1ca -[MyAnimeList
updatetitle:confirming:] + 1010
8   MAL Updater OS X                    0x000000010a2b90eb -[MyAnimeList
scrobble] + 1995
9   MAL Updater OS X                    0x000000010a2b3327
__41-[MAL_Updater_OS_XAppDelegate firetimer:]_block_invoke + 379
       0x10a2af000 -        0x10a2dafff +com.chikorita157.MAL-Updater-OS-X
(2.2.1 - 2.2.1) <06C3E93E-9797-3843-ABCC-BF95B8C8C1C3> /Applications/MAL
Updater OS X.app/Contents/MacOS/MAL Updater OS X
       0x10a307000 -        0x10a324ff7 +moe.ateliershiori.anitomy-osx (1.0
- 1) <1A8405C1-8518-3D2B-BC16-C097A506B08F> /Applications/MAL Updater OS
X.app/Contents/Frameworks/anitomy-osx.framework/Versions/A/anitomy-osx
       0x10a338000 -        0x10a3bdff7 +isao.sonobe.OgreKit (2.1.4)
<035D39AB-19B7-3811-A8B3-1BBEF344EEEA> /Applications/MAL Updater OS
X.app/Contents/Frameworks/OgreKit.framework/Versions/A/OgreKit
       0x10a3db000 -        0x10a409ff7 +org.andymatuschak.Sparkle (1.8.0 -
0b186dc) <3E8C44BB-5A29-3577-AC71-89DFAB4ECD19> /Applications/MAL Updater
OS X.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle

**Comment by heizenbrg** [comment] 2015-02-05 22:16
2/5/15 5:15:13.401 PM ReportCrash[878]: com.apple.message.domain:
com.apple.crashreporter.writereport.crash
com.apple.message.signature: MAL Updater OS X
com.apple.message.signature2: com.chikorita157.MAL-Updater-OS-X ||| 2.2.1
(2.2.1)
com.apple.message.signature3: DFE3E6FDF2EA8557DB03D4F57B8CAC9F
com.apple.message.result: NO
com.apple.message.summarize: YES
SenderMachUUID: 8C15E826-C574-3656-8CA9-235A0AC8C3BB

FILE NAME : [HorribleSubs] Cross Ange - 06 [1080p].mkv

**Comment by chikorita157** [comment] 2015-02-05 22:22
It may have to do with the GCD causing a deadlock with the async dispatch during the timer being fired (I have it like that so that the program won't freeze during the update process). I will look into it.

**Comment by chikorita157** [comment] 2015-02-05 22:49
Try this version to see if you have the same issue:
http://skitch.chikorita157.com/malupdaterosx-2.2.2b1-test.zip

There was one UI updating method in the async queue that is not in the main thread, so this might fix the issue you are having.

**Comment by heizenbrg** [comment] 2015-02-05 23:36
still crashing. Uninstalled everything including deleteing the crashes and
.plist
thanks though

**Comment by chikorita157** [comment] 2015-02-06 00:05
Sorry to hear that, but at least you tried as I don't know what the problem is (The program works perfectly on my computers and virtual machines). I will be closing this issue, but if you want another try, feel free to reopen the issue.

**Comment by chikorita157** [comment] 2015-02-08 17:40
I figured out the issue. It seems that NSMutableArray used for the HTTP request class is not thread which might be causing the problem judging from the crash report. Will be fixed in 2.2.3.

**Comment by chikorita157** [comment] 2015-02-08 17:41
Fixed with https://github.com/chikorita157/malupdaterosx-cocoa/commit/d07271c44bf18556fd24c26f420ca46091f3a87a

**Closed by chikorita157** 2015-02-08 17:41 UTC
Labels: bug

**Comment by heizenbrg** [comment] 2015-02-08 18:48
Hey thanks I'll check if it does alright now

**Comment by chikorita157** [comment] 2015-02-08 18:50
I haven't released it since it's for build 2.2.3... I will be releasing it after testing it.

**Comment by chikorita157** [comment] 2015-02-09 16:51
Here is the test build:
http://skitch.chikorita157.com/malupdaterosx-2.2.3-test.zip

I want you to unzip it, right click on the MAL Updater OS X and click Show Package Contents, open Contents > MacOS. Then click MAL Updater OS X. The terminal should show up. Attempt an update and then copy all the contents in the terminal window and put it in this issue.

**Comment by heizenbrg** [comment] 2015-02-10 02:15
This is what showed up:
Last login: Mon Feb  9 16:04:51 on console
-bash-3.2$ /Users/Heizenbrg/Downloads/MAL\ Updater\ OS\
X.app/Contents/MacOS/MAL\ Updater\ OS\ X ; exit;
2015-02-09 21:13:55.837 MAL Updater OS X[1534:27125] INFO -- Moving myself
to the Applications folder
2015-02-09 21:13:55.841 MAL Updater OS X[1534:27125] INFO -- Switching to
an already running version
logout

[Process completed]

**Comment by chikorita157** [comment] 2015-02-10 02:31
It seems that it moved to the applications folder in the users folder. Open the Applications folder in the Home Folder and Applications folder. Do the same (Right click on MAL Updater OS X > View Package Contents > Contents> MacOS and then click MAL Updater OS X). If the move dialog appears again, say don't move. Then attempt an update and then copy the terminal contents.
